// cloudfunctions/initGames/seeds.js
// 25 款精选游戏种子数据
// 封面统一使用 Steam CDN：https://cdn.akamai.steamstatic.com/steam/apps/{appid}/library_600x900.jpg
// 价格仅供参考，实际价格由 CheapShark 同步覆盖

const coverOf = (appid) => `https://cdn.akamai.steamstatic.com/steam/apps/${appid}/library_600x900.jpg`;
const headerOf = (appid) => `https://cdn.akamai.steamstatic.com/steam/apps/${appid}/header.jpg`;
const screenshotsOf = (appid, count = 4) =>
  Array.from({ length: count }, (_, i) =>
    `https://cdn.akamai.steamstatic.com/steam/apps/${appid}/ss_${i + 1}.jpg`
  );

module.exports = [
  // ============ 动作 ============
  {
    steam: 2358720,
    name: '黑神话：悟空',
    nameEn: 'Black Myth: Wukong',
    description: '《黑神话：悟空》是一款以中国神话为背景的动作角色扮演游戏。游戏的故事取材于中国古典小说"四大名著"之一的《西游记》。',
    rating: 9.4,
    price: 268,
    originalPrice: 268,
    tags: ['动作', '魂系', '中国', '剧情', '单人'],
    categoryId: 'cat_action',
    platforms: ['steam', 'ps5'],
    developer: 'Game Science',
    publisher: 'Game Science',
    releasedAt: '2024-08-20',
  },
  {
    steam: 1245620,
    name: '艾尔登法环',
    nameEn: 'ELDEN RING',
    description: '《艾尔登法环》是一款由 FromSoftware 制作的开放世界动作角色扮演游戏。在崩坏的"交界地"中开始一场壮丽的冒险。',
    rating: 9.5,
    price: 298,
    originalPrice: 298,
    tags: ['魂系', '开放世界', '黑暗奇幻', '困难', '剧情'],
    categoryId: 'cat_action',
    platforms: ['steam', 'ps5', 'xbox'],
    developer: 'FromSoftware',
    publisher: 'Bandai Namco',
    releasedAt: '2022-02-25',
  },
  {
    steam: 1091500,
    name: '赛博朋克 2077',
    nameEn: 'Cyberpunk 2077',
    description: '在巨型都市夜之城展开冒险，权力、奢靡与肉体改造令人沉醉。在这里，你将成为一名都市雇佣兵 V。',
    rating: 8.8,
    price: 298,
    originalPrice: 298,
    tags: ['赛博朋克', '开放世界', 'RPG', '剧情', 'FPS'],
    categoryId: 'cat_rpg',
    platforms: ['steam', 'ps5', 'xbox'],
    developer: 'CD PROJEKT RED',
    publisher: 'CD PROJEKT RED',
    releasedAt: '2020-12-10',
  },
  {
    steam: 268910,
    name: '茶杯头',
    nameEn: 'Cuphead',
    description: '《茶杯头》是一款经典的横版动作射击游戏，画面采用 1930 年代卡通风格，所有动画均为手绘。',
    rating: 9.3,
    price: 78,
    originalPrice: 78,
    tags: ['横版', '动作', '困难', '艺术', '独立'],
    categoryId: 'cat_action',
    platforms: ['steam', 'switch'],
    developer: 'Studio MDHR',
    publisher: 'Studio MDHR',
    releasedAt: '2017-09-29',
  },

  // ============ RPG ============
  {
    steam: 1086940,
    name: '博德之门 3',
    nameEn: "Baldur's Gate 3",
    description: '聚集你的队伍，回到被遗忘的国度，展开一段友情、背叛、牺牲、生存的故事，以及成为神祇的诱惑。',
    rating: 9.7,
    price: 298,
    originalPrice: 298,
    tags: ['RPG', '回合制', '剧情', 'CRPG', '多人'],
    categoryId: 'cat_rpg',
    platforms: ['steam', 'ps5'],
    developer: 'Larian Studios',
    publisher: 'Larian Studios',
    releasedAt: '2023-08-03',
  },
  {
    steam: 292030,
    name: '巫师 3：狂猎',
    nameEn: 'The Witcher 3: Wild Hunt',
    description: '猎魔人杰洛特将开始这场未完成的冒险，寻找命运中的孩子——传说中拥有强大力量的希里。',
    rating: 9.8,
    price: 127,
    originalPrice: 127,
    tags: ['RPG', '开放世界', '剧情', '奇幻', '单人'],
    categoryId: 'cat_rpg',
    platforms: ['steam', 'ps5', 'xbox'],
    developer: 'CD PROJEKT RED',
    publisher: 'CD PROJEKT RED',
    releasedAt: '2015-05-19',
  },
  {
    steam: 632470,
    name: '极乐迪斯科',
    nameEn: 'Disco Elysium',
    description: '革命性的开放式角色扮演游戏。你是一名侦探，可以塑造任何想要的警察类型——从超人到瘾君子。',
    rating: 9.4,
    price: 99,
    originalPrice: 99,
    tags: ['CRPG', '剧情', '艺术', '黑色幽默', '点击交互'],
    categoryId: 'cat_rpg',
    platforms: ['steam', 'ps5', 'switch'],
    developer: 'ZA/UM',
    publisher: 'ZA/UM',
    releasedAt: '2019-10-15',
  },

  // ============ 独立 ============
  {
    steam: 1145360,
    name: '哈迪斯',
    nameEn: 'Hades',
    description: '一款由 Supergiant Games 出品的 roguelike 地牢爬行动作游戏。扮演冥王哈迪斯的不朽王子，反抗你的父亲。',
    rating: 9.6,
    price: 88,
    originalPrice: 98,
    tags: ['Roguelike', '动作', '独立', '希腊神话', '剧情'],
    categoryId: 'cat_indie',
    platforms: ['steam', 'switch', 'ps5'],
    developer: 'Supergiant Games',
    publisher: 'Supergiant Games',
    releasedAt: '2020-09-17',
  },
  {
    steam: 367520,
    name: '空洞骑士',
    nameEn: 'Hollow Knight',
    description: '在被遗忘的废墟中，揭开虫之王国的秘密。一款 2D 类银河战士恶魔城游戏，拥有大量手绘的精美场景。',
    rating: 9.8,
    price: 45,
    originalPrice: 75,
    tags: ['类银河恶魔城', '独立', '困难', '艺术', '探索'],
    categoryId: 'cat_indie',
    platforms: ['steam', 'switch'],
    developer: 'Team Cherry',
    publisher: 'Team Cherry',
    releasedAt: '2017-02-25',
  },
  {
    steam: 413150,
    name: '星露谷物语',
    nameEn: 'Stardew Valley',
    description: '继承爷爷的旧农场，开启全新的乡村生活。种田、养殖、钓鱼、社交、探险，过你想要的人生。',
    rating: 9.7,
    price: 41,
    originalPrice: 56,
    tags: ['模拟经营', '种田', '治愈', '独立', '多人'],
    categoryId: 'cat_sim',
    platforms: ['steam', 'switch', 'ps5', 'ios'],
    developer: 'ConcernedApe',
    publisher: 'ConcernedApe',
    releasedAt: '2016-02-26',
  },
  {
    steam: 588650,
    name: '死亡细胞',
    nameEn: 'Dead Cells',
    description: '《死亡细胞》是一款融合 Roguelite 和类银河恶魔城元素的动作平台游戏。每次死亡都是新的开始。',
    rating: 9.5,
    price: 78,
    originalPrice: 98,
    tags: ['Roguelike', '动作', '类银河恶魔城', '困难', '独立'],
    categoryId: 'cat_indie',
    platforms: ['steam', 'switch', 'ios'],
    developer: 'Motion Twin',
    publisher: 'Motion Twin',
    releasedAt: '2018-08-07',
  },
  {
    steam: 504230,
    name: '蔚蓝',
    nameEn: 'Celeste',
    description: '帮助 Madeline 度过她内心的恐惧、克服外在的障碍，最终登上塞莱斯特山顶。一款手感极佳的横版跳跃游戏。',
    rating: 9.5,
    price: 68,
    originalPrice: 68,
    tags: ['平台跳跃', '困难', '独立', '剧情', '像素'],
    categoryId: 'cat_indie',
    platforms: ['steam', 'switch'],
    developer: 'Maddy Makes Games',
    publisher: 'Maddy Makes Games',
    releasedAt: '2018-01-25',
  },
  {
    steam: 391540,
    name: '传说之下',
    nameEn: 'Undertale',
    description: '一款独特的 RPG，怪物会和你战斗，你不必伤害任何一个敌人。一场充满温暖与诡异的旅程。',
    rating: 9.5,
    price: 36,
    originalPrice: 36,
    tags: ['RPG', '像素', '剧情', '独立', '艺术'],
    categoryId: 'cat_indie',
    platforms: ['steam', 'switch', 'ps5'],
    developer: 'tobyfox',
    publisher: 'tobyfox',
    releasedAt: '2015-09-15',
  },
  {
    steam: 1817190,
    name: '光遇',
    nameEn: 'Sky: Children of the Light',
    description: '在 thatgamecompany 打造的童话世界中翱翔，与全球玩家共享一场关于爱与希望的旅行。',
    rating: 9.0,
    price: 0,
    originalPrice: 0,
    tags: ['冒险', '剧情', '治愈', '多人', '免费'],
    categoryId: 'cat_adventure',
    platforms: ['ios', 'android', 'switch'],
    developer: 'thatgamecompany',
    publisher: 'thatgamecompany',
    releasedAt: '2019-06-18',
  },

  // ============ 模拟/经营 ============
  {
    steam: 1366540,
    name: '戴森球计划',
    nameEn: 'Dyson Sphere Program',
    description: '一款空间宏伟、内容硬核的模拟经营游戏。建造横跨星系的工厂网络，最终建成戴森球。',
    rating: 9.5,
    price: 70,
    originalPrice: 70,
    tags: ['模拟经营', '科幻', '中国', '自动化', '硬核'],
    categoryId: 'cat_sim',
    platforms: ['steam'],
    developer: 'Youthcat Studio',
    publisher: 'Gamera Game',
    releasedAt: '2021-01-21',
  },
  {
    steam: 457140,
    name: '缺氧',
    nameEn: 'Oxygen Not Included',
    description: '一款太空殖民地模拟游戏。带领你的复制人在外星岩石中建立可持续发展的栖息地。',
    rating: 9.4,
    price: 70,
    originalPrice: 88,
    tags: ['模拟经营', '生存', '建造', '独立', '硬核'],
    categoryId: 'cat_sim',
    platforms: ['steam'],
    developer: 'Klei Entertainment',
    publisher: 'Klei Entertainment',
    releasedAt: '2019-07-31',
  },
  {
    steam: 427520,
    name: '异星工厂',
    nameEn: 'Factorio',
    description: '一款关于建造和创造自动化工厂的游戏。建造越来越大、越来越复杂的工厂，自动化一切。',
    rating: 9.7,
    price: 102,
    originalPrice: 102,
    tags: ['模拟', '自动化', '建造', '独立', '硬核'],
    categoryId: 'cat_sim',
    platforms: ['steam', 'switch'],
    developer: 'Wube Software',
    publisher: 'Wube Software',
    releasedAt: '2020-08-14',
  },

  // ============ 策略 ============
  {
    steam: 289070,
    name: '文明 6',
    nameEn: "Sid Meier's Civilization VI",
    description: '体验文明的兴衰之路。带领你的人民从远古时代发展至信息时代，让你的文明流芳千古。',
    rating: 8.7,
    price: 199,
    originalPrice: 199,
    tags: ['回合制', '策略', '4X', '历史', '多人'],
    categoryId: 'cat_strategy',
    platforms: ['steam', 'switch', 'ios'],
    developer: 'Firaxis Games',
    publisher: '2K',
    releasedAt: '2016-10-21',
  },
  {
    steam: 281990,
    name: '群星',
    nameEn: 'Stellaris',
    description: '探索一个充满奇迹的银河系！策略游戏大师 Paradox 带来的大型太空 4X 策略游戏。',
    rating: 8.8,
    price: 99,
    originalPrice: 99,
    tags: ['4X', '太空', '策略', '科幻', '多人'],
    categoryId: 'cat_strategy',
    platforms: ['steam'],
    developer: 'Paradox',
    publisher: 'Paradox',
    releasedAt: '2016-05-09',
  },
  {
    steam: 646570,
    name: '杀戮尖塔',
    nameEn: 'Slay the Spire',
    description: '我们将卡牌构筑与 roguelike 结合到了一起，做出了我们梦想中的卡牌游戏。',
    rating: 9.6,
    price: 64,
    originalPrice: 64,
    tags: ['卡牌', 'Roguelike', '策略', '独立'],
    categoryId: 'cat_strategy',
    platforms: ['steam', 'switch', 'ios'],
    developer: 'MegaCrit',
    publisher: 'MegaCrit',
    releasedAt: '2019-01-23',
  },

  // ============ 多人/网游 ============
  {
    steam: 730,
    name: '反恐精英 2',
    nameEn: 'Counter-Strike 2',
    description: 'CS:GO 的升级版本，构建于全新 Source 2 引擎之上。免费游玩。',
    rating: 8.5,
    price: 0,
    originalPrice: 0,
    tags: ['FPS', '射击', '多人', '电竞', '免费'],
    categoryId: 'cat_action',
    platforms: ['steam'],
    developer: 'Valve',
    publisher: 'Valve',
    releasedAt: '2023-09-27',
  },
  {
    steam: 570,
    name: 'Dota 2',
    nameEn: 'Dota 2',
    description: '每天有数百万玩家加入战斗——他们都是 Dota 角色的扮演者。免费游玩。',
    rating: 8.2,
    price: 0,
    originalPrice: 0,
    tags: ['MOBA', '策略', '多人', '电竞', '免费'],
    categoryId: 'cat_strategy',
    platforms: ['steam'],
    developer: 'Valve',
    publisher: 'Valve',
    releasedAt: '2013-07-09',
  },
  {
    steam: 945360,
    name: 'Among Us',
    nameEn: 'Among Us',
    description: '在飞船和派对场景中扮演太空人或冒名顶替者，揭穿骗子、完成任务或破坏船只。',
    rating: 8.6,
    price: 25,
    originalPrice: 25,
    tags: ['多人', '社交推理', '休闲', '派对', '独立'],
    categoryId: 'cat_casual',
    platforms: ['steam', 'switch', 'ios', 'android'],
    developer: 'Innersloth',
    publisher: 'Innersloth',
    releasedAt: '2018-11-16',
  },
  {
    steam: 105600,
    name: '泰拉瑞亚',
    nameEn: 'Terraria',
    description: '挖掘、战斗、探索、建造！世界全靠你创造，可能性无穷尽。一切等你来决定。',
    rating: 9.7,
    price: 50,
    originalPrice: 50,
    tags: ['沙盒', '生存', '多人', '像素', '冒险'],
    categoryId: 'cat_sandbox',
    platforms: ['steam', 'switch', 'ios', 'android'],
    developer: 'Re-Logic',
    publisher: 'Re-Logic',
    releasedAt: '2011-05-16',
  },

  // ============ 解谜 ============
  {
    steam: 620,
    name: '传送门 2',
    nameEn: 'Portal 2',
    description: 'Valve 的标志性解谜游戏续作。在 Aperture Science 的实验室中使用传送门解决各种难题。',
    rating: 9.7,
    price: 36,
    originalPrice: 36,
    tags: ['解谜', '第一人称', '剧情', '多人', '经典'],
    categoryId: 'cat_puzzle',
    platforms: ['steam'],
    developer: 'Valve',
    publisher: 'Valve',
    releasedAt: '2011-04-18',
  },

].map((g) => ({
  // 统一字段处理
  externalIds: { steam: String(g.steam) },
  name: g.name,
  nameEn: g.nameEn,
  description: g.description,
  cover: coverOf(g.steam),
  headerImage: headerOf(g.steam),
  screenshots: screenshotsOf(g.steam, 4),
  rating: g.rating,
  ratingCount: 0,
  price: g.price,
  originalPrice: g.originalPrice,
  discount: g.originalPrice > 0 ? Math.round(((g.originalPrice - g.price) / g.originalPrice) * 100) : 0,
  storeUrls: {
    steam: `https://store.steampowered.com/app/${g.steam}/`,
  },
  tags: g.tags,
  categoryId: g.categoryId,
  platforms: g.platforms,
  developer: g.developer,
  publisher: g.publisher,
  releasedAt: g.releasedAt,
  videos: [],
  stats: {
    favCount: 0,
    viewCount: 0,
    steamOwners: 0,
    steamPositiveRate: 0,
  },
  dataSources: ['seed'],
  status: 1,
  // createdAt / updatedAt / lastSyncedAt 在写入时填充
}));
